name: Build nodejs workflow
on:
  push:
    branches: 
      - master 
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
     - name: Checkout Code 
       uses: actions/checkout@v6
     - name: Install nodejs
       uses: actions/setup-node@v6
       with:
          node-version: '18'
          cache: 'npm' # npm = node package manager
     - name: Install dependencies 
       run: npm ci # ci = clean install
     - name: Execute Test cases
       run: npm test
     - name: Build Code
       run: npm run build
     - name: Deploy code on server
       run: echo "Deploying code on server"
